spring.application.name=performance-optimization

# ==========================================
# DATABASE
# ==========================================

spring.datasource.url=jdbc:h2:mem:performance_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=create

spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# H2 CONSOLE
# ==========================================

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console

# ==========================================
# SERVER
# ==========================================

server.port=8080

# ==========================================
# LOGGING
# ==========================================

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.com.prionti.performanceoptimization=INFO